### ISSUE TITLE
Nav bar doesn't show properly

### ISSUE THREAD

**Issue by dlasagno** [vuejs/news.vuejs.org#10]
The about link doesn't stay inside the nav bar, so it overlaps with the articles' text. 

I was using the site on a mobile phone.

**Comment by ratracegrad** [comment]
I will submit a PR to resolve this issue by changing CSS styling for SM-DOWN size screen sizes. On smaller devices the screen will change to look like this.

![screen shot 2018-10-20 at 5 11 30 pm](https://user-images.githubusercontent.com/10262857/47260520-3e907f80-d48b-11e8-8496-af5f2a45c918.png)

**Comment by shentao** [comment]
Now merged. Thank you @ratracegrad!
