### ISSUE TITLE
Vue 3.0 release date

### ISSUE THREAD

**Issue by woothu** [vuejs/news.vuejs.org#17]
I cannot find any current information about the planned date of 3.0 version release. It would be very helpful to have some idea about the current approximate time of the release.

Regards

P.S. I have created this issue in documentation repo and the response was "not related to Vue documentation issues". If this repo is also not appropriate for this issue, let me know which is :)

**Comment by LinusBorg** [comment]
See: https://roadmap.vuejs.org

We don't commit to anything more specific, and always add: It will be released officially when it's done - we don't want to do it *quickly*, we want to do it *right*

**Comment by skewty** [comment]
The [roadmap](https://roadmap.vuejs.org/) has only a single [x] item as of Dec 21, 2019.  Is it simply not being updated or is the project way behind or something else?

**Comment by shentao** [comment]
It's just not updated, no worries!
