### ISSUE TITLE
The code is not working properly.

### ISSUE THREAD

**Issue by QC-L** [vuejs/news.vuejs.org#9]
I tried to run the project locally, but it failed.
error message: 
```
TypeError: Expected parameter accessToken
```
What should I do?

**Comment by shentao** [comment]
This one is tricky – I tried to abstain from publishing the preview keys for Contentful, but I guess that was a bad idea.
Here are the details you have to paste into `.env` file.
```
SPACE=fvjzlvrkinc4
ACCESS_TOKEN=4f4f9e133b04281c5b172963a693cc7881f8db9646426dd6bd179c646b6ee714
HOST=preview.contentful.com
```

**Comment by QC-L** [comment]
@shentao THX!
